// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://etblqytnblbfmptrxfbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0YmxxeXRuYmxiZm1wdHJ4ZmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzIzOTYsImV4cCI6MjA3MzI0ODM5Nn0.z5Pe6PsbdHz3Za-9o_0kUOl3dhC_V0EedWiSPcIN0vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});